version: "3"
services:
  express:
    build: .
    container_name: express    
    restart: always
    ports: 
    - 3000:3000
    volumes: 
    - .:/usr/app
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iantesting
    ports: 
    - 3306:3306